language: java
before_install: mvn install:install-file -Dfile=./external-repo/support-v4-19.1.0.jar -DgroupId=com.android.support -DartifactId=support-v4 -Dversion=19.1.0 -Dpackaging=jar
install: mvn install -DskipTests=true -Dgpg.skip=true
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
